title: Ahmed M Ali
url: "https://ahmed-mohsen-7.github.io/
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ahmed-mohsen-7"
footer_text: "Page design by Ankit Sultana and Ahmed Ali"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "Resume.pdf"
 - name: "Contact"
   link: "contact"
